import SwiftUI
import CoreML
import NaturalLanguage

struct ContentView: View {

    @State private var queryText  = ""
    @State private var prediction: String?
    @FocusState private var inputFocused: Bool

    // Load the model once at startup.
    // RecipeClassifier is auto-generated by Xcode from RecipeClassifier.mlmodel.
    private let nlModel: NLModel? = {
        guard let mlModel = try? RecipeClassifier(configuration: .init()).model else {
            return nil
        }
        return try? NLModel(mlModel: mlModel)
    }()

    var body: some View {
        NavigationStack {
            VStack(spacing: 24) {

                // ── Input ──────────────────────────────────────────────
                VStack(alignment: .leading, spacing: 8) {
                    Text("Your query")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)

                    TextField("e.g. How do I make tonkotsu ramen?",
                              text: $queryText,
                              axis: .vertical)
                        .textFieldStyle(.roundedBorder)
                        .lineLimit(3...6)
                        .focused($inputFocused)
                        .onSubmit { classify() }
                }

                // ── Action ─────────────────────────────────────────────
                Button {
                    classify()
                    inputFocused = false
                } label: {
                    Label("Classify", systemImage: "sparkle.magnifyingglass")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.large)
                .disabled(queryText.trimmingCharacters(in: .whitespaces).isEmpty)

                // ── Result ─────────────────────────────────────────────
                if let prediction {
                    VStack(spacing: 12) {
                        Text(emoji(for: prediction))
                            .font(.system(size: 72))

                        Text(prediction)
                            .font(.title.bold())
                            .foregroundStyle(.primary)

                        Text("< 1 ms · on-device · no network")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    .padding(24)
                    .frame(maxWidth: .infinity)
                    .background(.regularMaterial, in: RoundedRectangle(cornerRadius: 20))
                    .transition(.scale(scale: 0.85).combined(with: .opacity))
                }

                Spacer()
            }
            .padding()
            .animation(.spring(duration: 0.35), value: prediction)
            .navigationTitle("Recipe Classifier")
        }
    }

    // MARK: - Private

    private func classify() {
        let trimmed = queryText.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return }
        prediction = nlModel?.predictedLabel(for: trimmed) ?? "unknown"
    }

    private func emoji(for category: String) -> String {
        switch category {
        case "italian":       "🍝"
        case "mexican":       "🌮"
        case "asian":         "🍜"
        case "american":      "🍔"
        case "mediterranean": "🫒"
        case "breakfast":     "🥞"
        case "dessert":       "🍰"
        default:              "🍽️"
        }
    }
}

#Preview {
    ContentView()
}
